"""Divergent Generator: combinational creativity module.

Gives the agent the ability to GENERATE NOVEL IDEAS by combining existing
concepts from different domains, then evaluating their novelty and feasibility.

Three-stage pipeline:

1. DIVERGE — randomly sample concepts from different stores (rules, skills,
   variables) and combine them in unusual ways:
   - Rule A: "IF see key THEN pick up"
   - Skill B: "turn left"
   - Variable C: "∀X ∈ walls"
   - Combination: "IF wall is thin AND has tool THEN break wall" (novel idea)

2. EVALUATE — assess each combination for:
   - Novelty: has this combination been seen before? (check rule memory)
   - Coherence: does it make logical sense? (check LogicEngine)
   - Feasibility: can it be tested? (check HypothesisTester)
   - Value: could it lead to higher reward? (heuristic)

3. FILTER — keep the top-K most promising ideas:
   - High novelty + high coherence + high feasibility = creative idea
   - Low novelty or low coherence = discard

The generator is **divergent** (produces many ideas) followed by
**convergent** (filters to the best). This mirrors human creative thinking:
brainstorm → evaluate → select.

Bounded: max_ideas, max_combinations fixed. All stores are bounded.
VRAM: ~0.05 GB. Axiom 1 satisfied.

组合创造模块：发散（随机组合概念）→ 评估（新颖性+连贯性+可行性）→ 筛选（保留最优）。
模仿人类"头脑风暴 → 评估 → 选择"的创造过程。
"""

from __future__ import annotations

import logging
import random
from collections import deque
from dataclasses import dataclass, field
from typing import Any

import torch
import torch.nn as nn
import torch.nn.functional as F

logger = logging.getLogger(__name__)


# =====================================================================
# CreativeIdea: one generated combination
# =====================================================================


@dataclass
class CreativeIdea:
    """A single creative idea generated by divergent combination.

    - ``description``: human-readable text of the idea.
    - ``source_rules``: rule IDs that were combined.
    - ``source_skills``: skill IDs that were combined.
    - ``novelty_score``: 0-1, how novel (1 = never seen before).
    - ``coherence_score``: 0-1, how logically coherent.
    - ``feasibility_score``: 0-1, how testable.
    - ``overall_score``: weighted combination of the above.
    - ``tested``: whether this idea has been experimentally tested.
    - ``test_result``: outcome if tested.
    """
    id: int
    description: str
    source_rules: list[int] = field(default_factory=list)
    source_skills: list[int] = field(default_factory=list)
    novelty_score: float = 0.5
    coherence_score: float = 0.5
    feasibility_score: float = 0.5

    @property
    def overall_score(self) -> float:
        """Weighted: novelty 40% + coherence 30% + feasibility 30%."""
        return (
            0.4 * self.novelty_score
            + 0.3 * self.coherence_score
            + 0.3 * self.feasibility_score
        )

    def __repr__(self) -> str:
        return (
            f"Idea #{self.id}: {self.description} "
            f"(novel={self.novelty_score:.2f} "
            f"coherent={self.coherence_score:.2f} "
            f"feasible={self.feasibility_score:.2f} "
            f"overall={self.overall_score:.2f})"
        )


# =====================================================================
# DivergentGenerator: the creativity engine
# =====================================================================


class DivergentGenerator(nn.Module):
    """Combinational creativity: diverge → evaluate → filter.

    Usage:
        gen = DivergentGenerator(d_model=384)
        ideas = gen.generate(
            rules=rule_memory,
            skills=skill_library,
            logic_engine=logic_engine,
            n_ideas=20,
        )
        best = gen.filter(ideas, top_k=5)
        # Test the best idea via HypothesisTester or CodeExecutionEnv

    The generator does NOT train — it's a search/combination engine.
    All neural components are frozen (if any).

    Bounded: max_ideas_history fixed. All operations O(n_rules * n_skills).
    VRAM: ~0.05 GB (small scoring network). Axiom 1.
    """

    def __init__(
        self,
        d_model: int = 384,
        max_history: int = 256,
        novelty_weight: float = 0.4,
        coherence_weight: float = 0.3,
        feasibility_weight: float = 0.3,
    ) -> None:
        super().__init__()
        self._d_model = d_model
        self._novelty_w = novelty_weight
        self._coherence_w = coherence_weight
        self._feasibility_w = feasibility_weight
        self._max_history = int(max_history)
        self._history: deque[CreativeIdea] = deque(maxlen=self._max_history)  # BOUNDS-OK: maxlen bounded
        self._next_id = 0

        # Small scoring network: evaluates novelty of a combination
        # Input: concatenation of two concept embeddings → novelty score
        self.novelty_scorer = nn.Sequential(
            nn.Linear(d_model * 2, 64),
            nn.GELU(),
            nn.Linear(64, 1),
            nn.Sigmoid(),
        )

        # Coherence scorer: does the combination make sense?
        self.coherence_scorer = nn.Sequential(
            nn.Linear(d_model * 2, 64),
            nn.GELU(),
            nn.Linear(64, 1),
            nn.Sigmoid(),
        )

    @property
    def capacity(self) -> int:
        return self._max_history

    def __len__(self) -> int:
        return len(self._history)

    # ---------------------------------------------------------- DIVERGE

    def _diverge_rules(
        self,
        rules: list,  # list of rule-like objects with .condition_embedding and .action
        n_combinations: int,
    ) -> list[tuple]:
        """Randomly pair rules from different categories."""
        if len(rules) < 2:
            return []

        combinations: list[tuple] = []
        for _ in range(n_combinations):
            a, b = random.sample(rules, 2)
            combinations.append((a, b))
        return combinations

    def _diverge_skills(
        self,
        skills: list,  # list of skill-like objects with .weights
        n_combinations: int,
    ) -> list[tuple]:
        """Randomly pair skills."""
        if len(skills) < 2:
            return []

        combinations: list[tuple] = []
        for _ in range(n_combinations):
            a, b = random.sample(skills, 2)
            combinations.append((a, b))
        return combinations

    def _diverge_cross_domain(
        self,
        rules: list,
        skills: list,
        n_combinations: int,
    ) -> list[tuple]:
        """Cross-domain: pair a rule with a skill (most creative)."""
        if not rules or not skills:
            return []

        combinations: list[tuple] = []
        for _ in range(n_combinations):
            r = random.choice(rules)
            s = random.choice(skills)
            combinations.append((r, s))
        return combinations

    # ---------------------------------------------------------- EVALUATE

    def _evaluate_novelty(
        self,
        emb_a: torch.Tensor,
        emb_b: torch.Tensor,
        existing_rules: list,
    ) -> float:
        """How novel is this combination?

        High novelty = the two concepts are from very different regions
        of feature space AND no existing rule covers this combination.
        """
        with torch.no_grad():
            combined = torch.cat([emb_a, emb_b], dim=-1).unsqueeze(0)
            novelty = float(self.novelty_scorer(combined).item())

        # Check if any existing rule already covers this combination
        if existing_rules:
            for rule in existing_rules:
                rule_emb = getattr(rule, "condition_embedding", None)
                if rule_emb is not None:
                    sim = float(F.cosine_similarity(
                        emb_a.unsqueeze(0), rule_emb.unsqueeze(0), dim=1
                    ).item())
                    if sim > 0.9:
                        # This combination already exists → low novelty
                        novelty *= 0.3

        return novelty

    def _evaluate_coherence(
        self,
        emb_a: torch.Tensor,
        emb_b: torch.Tensor,
    ) -> float:
        """How coherent (logical) is this combination?

        High coherence = the two concepts are related enough to make
        a meaningful combination (not completely random).
        """
        with torch.no_grad():
            combined = torch.cat([emb_a, emb_b], dim=-1).unsqueeze(0)
            coherence = float(self.coherence_scorer(combined).item())

        # Also check cosine similarity: too similar = boring, too different = random
        sim = float(F.cosine_similarity(
            emb_a.unsqueeze(0), emb_b.unsqueeze(0), dim=1
        ).item())

        # Sweet spot: moderate similarity (0.2-0.7)
        if 0.2 <= sim <= 0.7:
            coherence = min(1.0, coherence + 0.2)
        elif sim > 0.9 or sim < 0.0:
            coherence *= 0.5  # too similar or opposite → less coherent

        return coherence

    def _evaluate_feasibility(
        self,
        action_a: int | None,
        action_b: int | None,
    ) -> float:
        """How feasible is it to test this combination?

        Simple heuristic: if both have concrete actions, it's testable.
        """
        if action_a is not None and action_b is not None:
            return 0.8
        elif action_a is not None or action_b is not None:
            return 0.5
        return 0.3

    # ---------------------------------------------------------- GENERATE

    def generate(
        self,
        rules: list | None = None,
        skills: list | None = None,
        n_ideas: int = 20,
    ) -> list[CreativeIdea]:
        """Generate creative ideas by combining existing concepts.

        Args:
            rules: list of rule objects (must have .condition_embedding and .action).
            skills: list of skill objects (must have .weights.A or .weights).
            n_ideas: number of ideas to generate.

        Returns:
            List of CreativeIdea, sorted by overall_score (best first).
        """
        rules = rules or []
        skills = skills or []

        # Extract embeddings
        rule_embeddings = []
        for r in rules:
            emb = getattr(r, "condition_embedding", None)
            act = getattr(r, "action", None)
            if emb is not None:
                rule_embeddings.append((emb, act, r))

        skill_embeddings = []
        for s in skills:
            weights = getattr(s, "weights", None)
            if weights is not None:
                # Use the flattened LoRA as embedding
                w = getattr(weights, "A", weights)
                emb = w.flatten()[:self._d_model]
                if emb.shape[0] < self._d_model:
                    emb = F.pad(emb, (0, self._d_model - emb.shape[0]))
                skill_embeddings.append((emb, None, s))

        ideas: list[CreativeIdea] = []

        # Diverge in three ways
        n_each = max(1, n_ideas // 3)

        # 1. Rule × Rule
        for a, b in self._diverge_rules(rule_embeddings, n_each):
            novelty = self._evaluate_novelty(a[0], b[0], rules)
            coherence = self._evaluate_coherence(a[0], b[0])
            feasibility = self._evaluate_feasibility(a[1], b[1])

            idea = CreativeIdea(
                id=self._next_id,
                description=f"IF {getattr(a[2], 'description', 'rule_A')} "
                           f"AND {getattr(b[2], 'description', 'rule_B')} "
                           f"THEN combine actions ({a[1]}, {b[1]})",
                source_rules=[id(a[2]), id(b[2])],
                novelty_score=novelty,
                coherence_score=coherence,
                feasibility_score=feasibility,
            )
            self._next_id += 1
            ideas.append(idea)

        # 2. Skill × Skill
        for a, b in self._diverge_skills(skill_embeddings, n_each):
            novelty = self._evaluate_novelty(a[0], b[0], [])
            coherence = self._evaluate_coherence(a[0], b[0])
            feasibility = 0.6  # skills can be composed via LoRA addition

            idea = CreativeIdea(
                id=self._next_id,
                description=f"Combine skill '{getattr(a[2], 'tag', 'skill_A')}' "
                           f"with '{getattr(b[2], 'tag', 'skill_B')}'",
                source_skills=[id(a[2]), id(b[2])],
                novelty_score=novelty,
                coherence_score=coherence,
                feasibility_score=feasibility,
            )
            self._next_id += 1
            ideas.append(idea)

        # 3. Cross-domain: Rule × Skill (most creative)
        for r_emb, s_emb in self._diverge_cross_domain(
            rule_embeddings, skill_embeddings, n_each
        ):
            novelty = self._evaluate_novelty(r_emb[0], s_emb[0], rules)
            coherence = self._evaluate_coherence(r_emb[0], s_emb[0])
            feasibility = 0.5  # cross-domain is harder to test

            idea = CreativeIdea(
                id=self._next_id,
                description=f"Apply rule '{getattr(r_emb[2], 'description', 'rule')}' "
                           f"using skill '{getattr(s_emb[2], 'tag', 'skill')}'",
                source_rules=[id(r_emb[2])],
                source_skills=[id(s_emb[2])],
                novelty_score=novelty,
                coherence_score=coherence,
                feasibility_score=feasibility,
            )
            self._next_id += 1
            ideas.append(idea)

        # Sort by overall score (best first)
        ideas.sort(key=lambda x: -x.overall_score)

        # Store in history (bounded)
        for idea in ideas[:self._max_history]:
            self._history.append(idea)

        return ideas

    # ---------------------------------------------------------- FILTER

    def filter(
        self,
        ideas: list[CreativeIdea],
        top_k: int = 5,
        min_novelty: float = 0.3,
        min_coherence: float = 0.3,
    ) -> list[CreativeIdea]:
        """Filter ideas to the most promising ones.

        Criteria:
        - Novelty >= min_novelty (must be genuinely new)
        - Coherence >= min_coherence (must make logical sense)
        - Feasibility > 0 (must be testable)
        - Top K by overall score
        """
        filtered = [
            idea for idea in ideas
            if idea.novelty_score >= min_novelty
            and idea.coherence_score >= min_coherence
            and idea.feasibility_score > 0
        ]
        filtered.sort(key=lambda x: -x.overall_score)
        return filtered[:top_k]

    # ---------------------------------------------------------- DIAGNOSTICS

    def get_best_ideas(self, n: int = 5) -> list[CreativeIdea]:
        """Get the N best ideas from history."""
        sorted_history = sorted(self._history, key=lambda x: -x.overall_score)
        return sorted_history[:n]

    def get_ideas_text(self, n: int = 10) -> list[str]:
        """Human-readable descriptions of the best ideas."""
        best = self.get_best_ideas(n)
        return [str(idea) for idea in best]

    def summary(self) -> dict:
        if not self._history:
            return {"total_ideas": 0, "capacity": self._max_history}
        return {
            "total_ideas": len(self._history),
            "capacity": self._max_history,
            "mean_novelty": sum(i.novelty_score for i in self._history) / len(self._history),
            "mean_coherence": sum(i.coherence_score for i in self._history) / len(self._history),
            "mean_feasibility": sum(i.feasibility_score for i in self._history) / len(self._history),
            "best_score": max(i.overall_score for i in self._history),
        }

    def state_dict(self) -> dict:
        return {
            "max_history": self._max_history,
            "next_id": self._next_id,
            "novelty_weight": self._novelty_w,
            "coherence_weight": self._coherence_w,
            "feasibility_weight": self._feasibility_w,
            "history": [
                {
                    "id": i.id,
                    "description": i.description,
                    "novelty": i.novelty_score,
                    "coherence": i.coherence_score,
                    "feasibility": i.feasibility_score,
                }
                for i in self._history
            ],
        }

    def load_state_dict(self, state: dict) -> None:
        self._max_history = int(state["max_history"])
        self._next_id = int(state["next_id"])
        self._novelty_w = float(state["novelty_weight"])
        self._coherence_w = float(state["coherence_weight"])
        self._feasibility_w = float(state["feasibility_weight"])
        self._history.clear()
        for i_dict in state["history"]:
            idea = CreativeIdea(
                id=i_dict["id"],
                description=i_dict["description"],
                novelty_score=i_dict["novelty"],
                coherence_score=i_dict["coherence"],
                feasibility_score=i_dict["feasibility"],
            )
            self._history.append(idea)
